
image: continuumio/miniconda3:latest

# GitLab Build and Deploy to a Server via SSH
# https://codeburst.io/gitlab-build-and-push-to-a-server-via-ssh-6d27ca1bf7b4

variables:
  GCP_PROJECT_ID: analitico-api
  GCP_ZONE: europe-west1

services:
- docker:dind

before_script:
  # Update environment
  - apt-get update -qq
  - apt-get install -y -qq python3-venv
  - apt-get install -y -qq python3-pip
  - apt-get install -y -qq sshpass

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - pip-cache

test:
  stage: test
  script:
    # Create virtual environment
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt
    # Prepare Django, run tests
    - cd source
    - ./manage.py collectstatic --noinput
    - ./manage.py test

deploy-staging:
  stage: deploy
  only:
    - master
  script:
    - export SSHPASS=$WWW_PASS 
    # sshpass -e scp -o stricthostkeychecking=no -r . www@s2.analitico.ai:/home/www/analitico
    - sshpass -e rsync -avzh --stats --progress . www@s2.analitico.ai:/home/www/analitico
    - sshpass -e ssh www@s2.analitico.ai "cd /home/www/analitico; source venv/bin/activate; pip3 install -r requirements.txt"
    - sshpass -e ssh www@s2.analitico.ai "cd /home/www/analitico; source venv/bin/activate; cd source; python3 manage.py collectstatic --noinput"
    - sshpass -e ssh www@s2.analitico.ai "cd /home/www/analitico; source venv/bin/activate; cd source; python3 manage.py test"
    # TODO python3 manage.py migrate
    # TODO sudo systemctl restart gunicorn_analitico

deploy-production:
  stage: deploy
  when: manual
  image: google/cloud-sdk:latest
  only:
    - master
  script:
    # Authenticate using the service account stored here: https://gitlab.com/groups/{YOUR_GITLAB_PROJECT}/-/settings/ci_cd
    - echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    # Deploy to Google Functions
    - cp requirements.txt -t source
    # gcloud functions deploy s24-order-sorting --entry-point handle_s24_order_sorting --source source --runtime python37 --trigger-http --region europe-west1
    # gcloud functions deploy v1 --entry-point handle_api --source source --runtime python37 --trigger-http --region europe-west1
