service: ep-xxxxxx # could be workspace id


frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7 # or python3.6, supported as of April 2017
  stage: production

  # https://docs.aws.amazon.com/general/latest/gr/rande.html#apigateway_region
  # region: eu-central-1
  region: us-east-1

package:
  include:
    - analitico/**
    - handler.py

functions:
  echo1: # could be endpoint id
    handler: handler.echo1
    events:
      - http:
          path: echo1 # could be the same as function name, endpoint id
          method: get 

  echo2:
    handler: handler.echo2
    events:
      - http:
          path: echo2
          method: get

  echo3:
    handler: handler.echo3
    events:
      - http:
          path: echo3
          method: get
