apiVersion: batch/v1
kind: Job
metadata:
  name: {job_id_slug}
  namespace: cloud
  labels:
    analitico.ai/workspace-id: {workspace_id}
    analitico.ai/item-id: {item_id}
    analitico.ai/target-id: {target_id}
    analitico.ai/job-id: {job_id}
spec:
  # no retries
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      # run docker deamon in support to the builder
      - name: docker-deamon
        image: docker:stable-dind
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-storage
          mountPath: /var/lib/docker
      - name: build-job-container
        image: {build_image}
        command: {build_command}
        env:
        - name: ANALITICO_WORKSPACE_ID
          value: {workspace_id}
        - name: ANALITICO_ITEM_ID
          value: {item_id}
        - name: ANALITICO_ITEM_PATH
          value: $ANALITICO_DRIVE/{item_type}s/{item_id}
        - name: ANALITICO_JOB_ID
          value: {job_id}
        - name: ANALITICO_TARGET_ID
          value: {target_id}
        - name: ANALITICO_DRIVE
          value: /mnt/analitico-drive
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        volumeMounts:
        - name: analitico-drive
          mountPath: /mnt/analitico-drive
          readOnly: false
      volumes:
      - name: analitico-drive
        flexVolume:
          driver: fstab/cifs
          fsType: cifs
          secretRef:
            name: analitico-drive-{workspace_id_slug}
          options:
            networkPath: {volume_network_path}
            mountOptions: dir_mode=0755,file_mode=0644,noperm
      - name: docker-storage
        emptyDir: {{}}
