# Generated by Django 2.1.3 on 2018-12-01 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.SlugField(default=django.utils.crypto.get_random_string, max_length=32, primary_key=True, serialize=False, verbose_name='Key')),
                ('name', models.SlugField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('user', 'name')},
        ),
    ]
