# Generated by Django 2.1.3 on 2019-01-09 08:18

import api.models.items
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('api', '0001_squashed_0009_auto_20181215_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.SlugField(default=api.models.items.generate_dataset_id, primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.TextField(blank=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('attributes', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Attributes')),
            ],
            bases=(api.models.items.AttributesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.SlugField(default=api.models.items.generate_model_id, primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.TextField(blank=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('attributes', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Attributes')),
            ],
            bases=(api.models.items.AttributesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.SlugField(default=api.models.items.generate_recipe_id, primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.TextField(blank=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('attributes', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Attributes')),
            ],
            bases=(api.models.items.AttributesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.SlugField(default=api.models.items.generate_service_id, primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.TextField(blank=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('attributes', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Attributes')),
            ],
            bases=(api.models.items.AttributesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.SlugField(default=api.models.items.generate_workspace_id, primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.TextField(blank=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('attributes', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Attributes')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='Group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            bases=(api.models.items.AttributesMixin, models.Model),
        ),
        migrations.AddField(
            model_name='service',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Workspace'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Workspace'),
        ),
        migrations.AddField(
            model_name='model',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Workspace'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Workspace'),
        ),
    ]
