# Generated by Django 2.1.3 on 2018-11-29 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', jsonfield.fields.JSONField(verbose_name='Data sent to the API')),
                ('results', jsonfield.fields.JSONField(verbose_name='Response from the API')),
                ('status', models.IntegerField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User who called the API')),
            ],
        ),
    ]
