# Generated by Django 2.1.3 on 2018-11-29 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_inference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inference',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='inference',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='inference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inference',
            name='data',
            field=jsonfield.fields.JSONField(null=True, verbose_name='Data sent to the API'),
        ),
        migrations.AlterField(
            model_name='inference',
            name='results',
            field=jsonfield.fields.JSONField(null=True, verbose_name='Response from the API'),
        ),
        migrations.AlterField(
            model_name='inference',
            name='status',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='inference',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User who called the API'),
        ),
    ]
