# Generated by Django 2.1.3 on 2018-11-30 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('api', '0003_auto_20181129_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('settings', jsonfield.fields.JSONField(null=True)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='Group that has access to this model')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner of this model')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.SlugField(default='Kr6yU3', max_length=6, primary_key=True, serialize=False)),
                ('scores', jsonfield.fields.JSONField(null=True, verbose_name='Training scores and information')),
                ('notes', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Model', verbose_name='Model that was trained')),
            ],
        ),
        migrations.AlterField(
            model_name='inference',
            name='data',
            field=jsonfield.fields.JSONField(null=True, verbose_name='Request received'),
        ),
        migrations.AlterField(
            model_name='inference',
            name='id',
            field=models.SlugField(default='a8yTIt', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inference',
            name='results',
            field=jsonfield.fields.JSONField(null=True, verbose_name='Response sent'),
        ),
        migrations.AlterField(
            model_name='inference',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User who called the API'),
        ),
        migrations.AddField(
            model_name='inference',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Training'),
        ),
    ]
