# Generated by Django 2.1.5 on 2019-02-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190131_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='subtype',
        ),
        migrations.AddField(
            model_name='job',
            name='action',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
