# Generated by Django 2.1.3 on 2018-11-30 12:34

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181130_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='training_id',
            field=models.SlugField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='inference',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, default='', verbose_name='Request received'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inference',
            name='id',
            field=models.SlugField(default='VfRlvE', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inference',
            name='results',
            field=jsonfield.fields.JSONField(blank=True, default='', verbose_name='Response sent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='settings',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='id',
            field=models.SlugField(default='4jc8Ut', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='training',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='scores',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Training scores and information'),
        ),
    ]
