# Generated by Django 2.1.3 on 2018-12-02 15:32

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181202_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='settings',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
