# Generated by Django 2.1.5 on 2019-03-06 14:45

import api.models.dataset
import api.models.items
import api.models.log
import api.models.model
import api.models.workspace
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("api", "0005_endpoint")]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id", models.SlugField(default=api.models.log.generate_log_id, primary_key=True, serialize=False)),
                ("item_id", models.SlugField(blank=True)),
                ("level", models.IntegerField(db_index=True, default=0)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("attributes", jsonfield.fields.JSONField(blank=True, null=True)),
            ],
            bases=(api.models.items.ItemMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="dataset", name="attributes", field=jsonfield.fields.JSONField(blank=True, null=True)
        ),
        migrations.AlterField(model_name="dataset", name="created_at", field=models.DateTimeField(auto_now_add=True)),
        migrations.AlterField(model_name="dataset", name="description", field=models.TextField(blank=True)),
        migrations.AlterField(
            model_name="dataset",
            name="id",
            field=models.SlugField(default=api.models.dataset.generate_dataset_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(model_name="dataset", name="title", field=models.TextField(blank=True)),
        migrations.AlterField(model_name="dataset", name="updated_at", field=models.DateTimeField(auto_now=True)),
        migrations.AlterField(
            model_name="model", name="attributes", field=jsonfield.fields.JSONField(blank=True, null=True)
        ),
        migrations.AlterField(model_name="model", name="created_at", field=models.DateTimeField(auto_now_add=True)),
        migrations.AlterField(model_name="model", name="description", field=models.TextField(blank=True)),
        migrations.AlterField(
            model_name="model",
            name="id",
            field=models.SlugField(default=api.models.model.generate_model_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(model_name="model", name="title", field=models.TextField(blank=True)),
        migrations.AlterField(model_name="model", name="updated_at", field=models.DateTimeField(auto_now=True)),
        migrations.AlterField(
            model_name="recipe", name="attributes", field=jsonfield.fields.JSONField(blank=True, null=True)
        ),
        migrations.AlterField(model_name="recipe", name="created_at", field=models.DateTimeField(auto_now_add=True)),
        migrations.AlterField(model_name="recipe", name="description", field=models.TextField(blank=True)),
        migrations.AlterField(model_name="recipe", name="title", field=models.TextField(blank=True)),
        migrations.AlterField(model_name="recipe", name="updated_at", field=models.DateTimeField(auto_now=True)),
        migrations.AlterField(model_name="token", name="created_at", field=models.DateTimeField(auto_now_add=True)),
        migrations.AlterField(model_name="token", name="updated_at", field=models.DateTimeField(auto_now=True)),
        migrations.AlterField(
            model_name="token",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user", name="attributes", field=jsonfield.fields.JSONField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="workspace", name="attributes", field=jsonfield.fields.JSONField(blank=True, null=True)
        ),
        migrations.AlterField(model_name="workspace", name="created_at", field=models.DateTimeField(auto_now_add=True)),
        migrations.AlterField(model_name="workspace", name="description", field=models.TextField(blank=True)),
        migrations.AlterField(
            model_name="workspace",
            name="group",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="auth.Group"
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="id",
            field=models.SlugField(
                default=api.models.workspace.generate_workspace_id, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(model_name="workspace", name="title", field=models.TextField(blank=True)),
        migrations.AlterField(model_name="workspace", name="updated_at", field=models.DateTimeField(auto_now=True)),
        migrations.AlterField(
            model_name="workspace",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="workspace",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Workspace"
            ),
        ),
    ]
