# Generated by Django 2.1.3 on 2018-11-30 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181130_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inference',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Request received'),
        ),
        migrations.AlterField(
            model_name='inference',
            name='id',
            field=models.SlugField(default='AkQGvs', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inference',
            name='results',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Response sent'),
        ),
        migrations.AlterField(
            model_name='inference',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Training'),
        ),
        migrations.AlterField(
            model_name='inference',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User who called the API'),
        ),
        migrations.AlterField(
            model_name='model',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='Group that has access to this model'),
        ),
        migrations.AlterField(
            model_name='model',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner of this model'),
        ),
        migrations.AlterField(
            model_name='training',
            name='id',
            field=models.SlugField(default='PXcC3L', max_length=6, primary_key=True, serialize=False),
        ),
    ]
