# Generated by Django 2.1.3 on 2018-12-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181206_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='status',
            field=models.SlugField(blank=True, default='Created'),
        ),
    ]
