# Generated by Django 2.1.5 on 2019-03-07 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0006_auto_20190306_1545")]

    operations = [
        migrations.AddField(
            model_name="log",
            name="job",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Job"),
        )
    ]
