# Generated by Django 2.1.3 on 2018-12-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_training_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set(),
        ),
    ]
