# Generated by Django 2.1.5 on 2019-03-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0007_log_job")]

    operations = [
        migrations.AlterField(model_name="log", name="item_id", field=models.SlugField(blank=True, null=True))
    ]
