# Generated by Django 2.1.5 on 2019-03-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0008_auto_20190308_1302")]

    operations = [migrations.RenameField(model_name="log", old_name="message", new_name="title")]
