# Generated by Django 2.1.3 on 2018-12-15 16:56

import api.models.token
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181213_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ('created_at',)},
        ),
        migrations.RemoveField(
            model_name='token',
            name='key',
        ),
        migrations.AddField(
            model_name='token',
            name='id',
            field=models.SlugField(default=api.models.token.generate_token_id, max_length=32, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
