# Generated by Django 2.1.5 on 2019-03-16 14:22

import api.models.items
import api.models.notebook
import api.models.recipe
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("api", "0009_auto_20190312_1948")]

    operations = [
        migrations.CreateModel(
            name="Notebook",
            fields=[
                (
                    "id",
                    models.SlugField(
                        default=api.models.notebook.generate_notebook_id, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attributes", jsonfield.fields.JSONField(blank=True, null=True)),
                ("notebook", jsonfield.fields.JSONField(blank=True, null=True)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.Workspace")),
            ],
            bases=(api.models.items.ItemMixin, api.models.items.ItemAssetsMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="id",
            field=models.SlugField(default=api.models.recipe.generate_recipe_id, primary_key=True, serialize=False),
        ),
    ]
