# Generated by Django 2.1.5 on 2019-03-20 14:40

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("api", "0010_auto_20190316_1522")]

    operations = [
        migrations.AddField(
            model_name="dataset", name="notebook", field=jsonfield.fields.JSONField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name="recipe", name="notebook", field=jsonfield.fields.JSONField(blank=True, null=True)
        ),
    ]
