# Generated by Django 2.1.5 on 2019-03-24 07:42

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("api", "0011_auto_20190320_1540")]

    operations = [
        migrations.AddField(
            model_name="model", name="notebook", field=jsonfield.fields.JSONField(blank=True, null=True)
        )
    ]
