# Generated by Django 2.1.5 on 2019-05-19 08:52

import api.models.items
import api.models.role
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("api", "0012_model_notebook")]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.SlugField(default=api.models.role.generate_role_id, primary_key=True, serialize=False)),
                ("roles", models.TextField(null=True)),
                ("permissions", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attributes", jsonfield.fields.JSONField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.Workspace")),
            ],
            bases=(api.models.items.ItemMixin, models.Model),
        )
    ]
