# Generated by Django 2.1.5 on 2019-05-19 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0013_role")]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="roles", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="roles", to="api.Workspace"
            ),
        ),
    ]
