# Generated by Django 2.2.1 on 2019-07-05 10:08

import api.models.drive
import api.models.items
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("api", "0015_auto_20190519_1703")]

    operations = [
        migrations.CreateModel(
            name="Drive",
            fields=[
                ("id", models.SlugField(default=api.models.drive.generate_drive_id, primary_key=True, serialize=False)),
                ("title", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attributes", jsonfield.fields.JSONField(blank=True, null=True)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.Workspace")),
            ],
            bases=(api.models.items.ItemMixin, api.models.items.ItemAssetsMixin, models.Model),
        )
    ]
