# Generated by Django 2.2.1 on 2019-07-05 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0016_drive")]

    operations = [
        migrations.AlterField(
            model_name="drive",
            name="workspace",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Workspace"),
        )
    ]
