# Generated by Django 2.2.1 on 2019-07-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0017_auto_20190705_1227")]

    operations = [migrations.RemoveField(model_name="drive", name="workspace")]
