# Generated by Django 2.2.4 on 2020-01-15 15:42

import api.models.automl
import api.models.items
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_drive_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automl',
            fields=[
                ('id', models.SlugField(default=api.models.automl.generate_automl_id, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', jsonfield.fields.JSONField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Workspace')),
            ],
            bases=(api.models.items.ItemMixin, models.Model),
        ),
    ]
