apiVersion: batch/v1
kind: Job
metadata:
  name: {job_id_slug}
  namespace: cloud
  labels:
    analitico.ai/workspace-id: {workspace_id}
    analitico.ai/item-id: {item_id}
    analitico.ai/job-action: {job_action}
    analitico.ai/job-id: {job_id}
    analitico.ai/dataset-hash: {dataset_hash}
spec:
  # no retries
  backoffLimit: 0
  template:
    metadata:
      labels:
        analitico.ai/workspace-id: {workspace_id}
        analitico.ai/item-id: {item_id}
        analitico.ai/dataset-hash: {dataset_hash}
    spec:
      # used to schedule the job in the reserved nodes with a lot of RAM and CPUs
      tolerations:
      - key: "analitico.ai/automl"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: run-job-container
        image: {run_image}
        command: {run_command}
        env:
        - name: ANALITICO_WORKSPACE_ID
          value: {workspace_id}
        - name: ANALITICO_ITEM_ID
          value: {item_id}
        - name: ANALITICO_ITEM_PATH
          value: /mnt/analitico-drive/{item_type}s/{item_id}
        - name: ANALITICO_JOB_ID
          value: {job_id}
        - name: ANALITICO_DRIVE
          value: /mnt/analitico-drive
        - name: ANALITICO_JOB_ACTION
          value: {job_action}
        - name: ANALITICO_NOTIFICATION_URL
          value: {notification_url}
{env_vars}
        volumeMounts:
        - name: analitico-drive
          mountPath: /mnt/analitico-drive
          readOnly: false
        resources:
          requests:
            cpu: {cpu_request}
            memory: {memory_request}
          limits:
            cpu: {cpu_limit}
            memory: {memory_limit}
      restartPolicy: Never
      volumes:
      - name: analitico-drive
        flexVolume:
          driver: fstab/cifs
          fsType: cifs
          secretRef:
            name: analitico-drive-{workspace_id_slug}
          options:
            networkPath: {volume_network_path}
            mountOptions: dir_mode=0755,file_mode=0644,noperm
