apiVersion: batch/v1
kind: Job
metadata:
  name: {job_id_slug}
  namespace: cloud
  labels:
    analitico.ai/workspace-id: {workspace_id}
    analitico.ai/item-id: {item_id}
    analitico.ai/target-id: {target_id}
    analitico.ai/job-action: {job_action}
    analitico.ai/job-id: {job_id}
  annotations:
    analitico.ai/notebook-name: {notebook_name}
spec:
  # eg, packages download error
  backoffLimit: 3
  template:
    metadata:
      labels:
        analitico.ai/workspace-id: {workspace_id}
        analitico.ai/item-id: {item_id}
        analitico.ai/target-id: {target_id}
      annotations:
        analitico.ai/notebook-name: {notebook_name}
    spec:
      restartPolicy: Never
      initContainers:
        # first run the notebook or recipe in an untrusted docker
      - name: run-job-container
        image: {run_image}
        command: {run_command}
        env:
        - name: ANALITICO_WORKSPACE_ID
          value: {workspace_id}
        - name: ANALITICO_ITEM_ID
          value: {item_id}
        - name: ANALITICO_ITEM_PATH
          value: /mnt/analitico-drive/{item_type}s/{item_id}
        - name: ANALITICO_JOB_ID
          value: {job_id}
        - name: ANALITICO_BLESSED_MODEL_ID
          value: {blessed_model_id}
        - name: ANALITICO_DRIVE
          value: /mnt/analitico-drive
        - name: ANALITICO_JOB_ACTION
          value: {job_action}
        - name: ANALITICO_NOTIFICATION_URL
          value: {notification_url}
{env_vars}
        volumeMounts:
        - name: analitico-drive
          mountPath: /mnt/analitico-drive
          readOnly: false
        resources:
          requests:
            cpu: 500m
            memory: 28Gi
          limits:
            cpu: 4
            memory: 64Gi
#           nvidia.com/gpu: 1
      containers:
      # build item into a docker, push to registry, store docker information
      - name: build-job-container
        image: {build_image}
        command: {build_command}
        env:
        - name: ANALITICO_WORKSPACE_ID
          value: {workspace_id}
        - name: ANALITICO_ITEM_ID
          value: {item_id}
        - name: ANALITICO_ITEM_PATH
          value: /mnt/analitico-drive/{item_type}s/{item_id}
        - name: ANALITICO_JOB_ID
          value: {job_id}
        - name: ANALITICO_TARGET_ID
          value: {target_id}
        - name: ANALITICO_DRIVE
          value: /mnt/analitico-drive
        - name: ANALITICO_JOB_ACTION
          value: {job_action}
        - name: ANALITICO_NOTIFICATION_URL
          value: {notification_url}
        securityContext:
          privileged: true
        volumeMounts:
        - name: analitico-drive
          mountPath: /mnt/analitico-drive
          readOnly: false
        - name: docker-storage
          mountPath: /var/lib/docker
        resources:
          requests:
            cpu: 100m
            memory: 4Gi
          limits:
            cpu: 1
            memory: 6Gi
      volumes:
      - name: analitico-drive
        flexVolume:
          driver: fstab/cifs
          fsType: cifs
          secretRef:
            name: analitico-drive-{workspace_id_slug}
          options:
            networkPath: {volume_network_path}
            mountOptions: dir_mode=0755,file_mode=0644,noperm
      - name: docker-storage
        emptyDir: {{}}
