apiVersion: v1
kind: Service
metadata:
  name: {service_name}
  namespace: {service_namespace}
  labels:
    app: {service_name}
    analitico.ai/service: jupyter
    analitico.ai/workspace-id: {workspace_id}
  annotations:
    analitico.ai/jupyter-url: "{service_url}"
spec:
  selector:
    app: {service_name}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
