apiVersion: v1
kind: Secret
metadata:
  name: {secret_name}
  namespace: {service_namespace}
  labels:
    app: {service_name}
    analitico.ai/service: jupyter
    analitico.ai/workspace-id: {workspace_id}
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    kind: Service
    name: {service_name}
    uid: {owner_uid}
type: Opaque
data:
  token: {jupyter_token}
