apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: {service_name}
  namespace: {service_namespace}
spec:
  template:
    spec:
      containers:
      - image: {docker_image}
        command: ["./serverless-start.sh"]
        env:
        - name: ANALITICO_SERVICE_NAME
          value: "{service_name}"
        - name: ANALITICO_ITEM_ID
          value: "{item_id}"
