apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {service_name}
  namespace: {service_namespace}
  labels:
    analitico.ai/workspace-id: {workspace_id}
    analitico.ai/item-id: {item_id}
    analitico.ai/service: "serving"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "{autoscaling_min_scale}"
        autoscaling.knative.dev/maxScale: "{autoscaling_max_scale}"
        autoscaling.knative.dev/class: "{autoscaling_class}"
        autoscaling.knative.dev/metric: "{autoscaling_metric}"
        autoscaling.knative.dev/target: "{autoscaling_target}"
      labels:
        analitico.ai/workspace-id: {workspace_id}
        analitico.ai/item-id: {item_id}
        analitico.ai/service: "serving"
    spec:
      containers:
      - image: {docker_image}
        imagePullPolicy: Always
        command: {command}
        env:
        - name: ANALITICO_SERVICE_NAME
          value: "{service_name}"
        - name: ANALITICO_ITEM_ID
          value: "{item_id}"
        - name: ANALITICO_API_TOKEN
          value: "{api_token}"
        - name: LOG_LEVEL
          value: "{log_level}"
        resources:
          limits:
            cpu: 4
            memory: 18Gi
          requests:
            cpu: 500m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health
          initialDelaySeconds: 5
          timeoutSeconds: 30
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
          initialDelaySeconds: 5
          timeoutSeconds: 10
          periodSeconds: 20
          failureThreshold: 6



