apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: {service_name}
  namespace: {service_namespace}
  labels:
    analitico.ai/workspace-id: {workspace_id}
    analitico.ai/item-id: {item_id}
spec:
  template:
    metadata:
      labels:
        analitico.ai/workspace-id: {workspace_id}
        analitico.ai/item-id: {item_id}
    spec:
      containers:
      - image: {docker_image}
        command: ["./tasks/serverless-start.sh"]
        env:
        - name: ANALITICO_SERVICE_NAME
          value: "{service_name}"
        - name: ANALITICO_ITEM_ID
          value: "{item_id}"
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 2Gi


